cmake_minimum_required(VERSION 3.11)
project(TheStochasticDungeon)
set(CMAKE_TLS_VERIFY OFF)
set(CMAKE_CXX_STANDARD 17)
include(FetchContent)
FetchContent_Declare(raylib URL https://github.com/raysan5/raylib/archive/master.tar.gz)
FetchContent_MakeAvailable(raylib)
file(GLOB_RECURSE SOURCES "src/*.cpp")
add_executable(${PROJECT_NAME} ${SOURCES})
target_include_directories(${PROJECT_NAME} PRIVATE include)
target_link_libraries(${PROJECT_NAME} PRIVATE raylib)
